name: Build NTK Ultra-Compression

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.os }}
    
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Linux
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            binary_path: target/release/ntk-ultra-compression
            asset_name: ntk-ultra-compression-linux-amd64
          
          - name: Windows
            os: windows-latest
            target: x86_64-pc-windows-msvc
            binary_path: target/release/ntk-ultra-compression.exe
            asset_name: ntk-ultra-compression-windows-amd64.exe
          
          - name: macOS
            os: macos-latest
            target: x86_64-apple-darwin
            binary_path: target/release/ntk-ultra-compression
            asset_name: ntk-ultra-compression-macos-amd64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.platform.target }}
          override: true
          profile: minimal

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: gui/package-lock.json

      - name: Install Linux dependencies
        if: matrix.platform.os == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Install dependencies
        working-directory: gui
        run: npm install

      - name: Build Tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: gui
          tagName: ${{ github.ref_name }}
          releaseName: "NTK Ultra-Compression v${{ github.ref_name }}"
          releaseBody: "See the assets to download this version and install."
          releaseDraft: true
          prerelease: false

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.asset_name }}
          path: ${{ matrix.platform.binary_path }}
          if-no-files-found: error

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/ntk-ultra-compression-linux-amd64/ntk-ultra-compression-linux-amd64
            artifacts/ntk-ultra-compression-windows-amd64.exe/ntk-ultra-compression-windows-amd64.exe
            artifacts/ntk-ultra-compression-macos-amd64/ntk-ultra-compression-macos-amd64
          draft: true
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 